services:
  mysql:
    image: mysql:8.4
    container_name: careerlink-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: K04
      MYSQL_DATABASE: careerlink
    ports:
      - "3306:3306"
    volumes:
      - careerlink_mysql_data:/var/lib/mysql

volumes:
  careerlink_mysql_data:
